### PR TITLE
feat: adding response protocol

### PR DESCRIPTION
**Pull request by kehiy**
## Description
Adding a protocol specification for better response sending. also, we can update our data type and accept `byte` as the value of each element. for the last steps before implementation, we need to make sure it's compatible with TQL or maybe combine them into one thing to reduce complexity. 

## Related Issue

- Related #90

### CODE REVIEW

**Review by 0x9n0p — APPROVED** [review]

**Comment by kehiy** [comment]
@0x9n0p is everything ok in this specification?

**Comment by kehiy** [comment]
@0x9n0p any updates on this?

**Comment by 0x9n0p** [comment]
No. I'll work on it tomorrow.

**Comment by kehiy** [comment]
@0x9n0p Ok, waiting for your updates. ping me on telegram or discord for any help or question. lets finalise that!

**Pull request closed without merging**
